### PR TITLE
hotfix pymysql

### PR DESCRIPTION
**Pull request by RobertEng**
### Summary
- Hotfix for the rest of sqlalchemy to pymysql conversion. Missed a few instances and was crashing account creation.

### Test Plan
- There were no tests for account creation other than manually.

@joshc

### CODE REVIEW

**Review by calebsander — DISMISSED** [review]
lgtm

**Comment by calebsander** [comment]
Except `make lint` is failing

**Review by joshc — COMMENTED** [review]
Seems like some things are failing.
image

**Review by joshc — CHANGES_REQUESTED** [review]
Ran `make lint` which yielded the errors from `make test`. Please fix those errors. Seems like there still needs to be some clean up done with regards to how transactions are differently represented in pymysql vs sqlalchemy.

**Comment by calebsander** [comment]
I think we should probably leave `sqlalchemy` in as a requirement for now so that the marketplace tests don't fail. Once Thomas merges in the new marketplace we should be able to get rid of it.

**Comment by RobertEng** [comment]
Yea, that's what i was thinking

**Review by joshc — APPROVED** [review]

**Comment by joshc** [comment]
lgtm

**Pull request merged**
