### PR TITLE
Added endpoint for listing members by group

### PR DESCRIPTION
**Pull request by davistardif**
### Summary
- Created endpoint for members by group (/1/groups/4/members/)

### Test Plan
- test on http://localhost:9000/1/groups/<group_id>/members/
- Also check http://localhost:9000/1/members/<user_id>
- Run `make test`

### CODE REVIEW

**Comment by davistardif** [comment]
Currently uses [Core Module](https://github.com/ASCIT/donut/blob/master/donut/modules/core/helpers.py) to get data about each user id. Would be more efficient to use a join instead of generating a query for each user id, but to do that this module needs access to `default_fields` from the function `get_member_data(user_id, fields=None)` in the core module.

**Comment by dqu123** [comment]
@davistardif yeah it's pretty inefficient to make a database call for each user.
You can adapt `get_member_data` to take in a list of user_ids, and for the case where you want a single member, to just return the single result instead of a list.

**Comment by davistardif** [comment]
@dqu123 Added you suggestion. Adding core module to test plan in case I broke anything while editing `get_member_data`

**Comment by davistardif** [comment]
Ready for review

**Review by majesticfish — APPROVED** [review]
looks good to me!

**Pull request merged**
